#Purpose of this file is store the application URL
#Maintain the application credentials
#Maintain the browser configuration
#Which browser to be used

Browser=Chrome

URL=https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login
UserName=abc
Password=abcd

KillExistingBrowsers=True
BrowserClose=False

Incognito=False

#Code will be executed in the Background
Headless=False 